### PR TITLE
Generate literals for negative numbers

### LINKED ISSUE #66: Optimize negation of number literals
The code `-4` compiles to `$negate(4)`. This is unnecessary because we already know numeric literals can't fail the assertion in `$negate`, so we should optimize to simply `-4` in the output.

This should just be checking the argument type in `negate.js` for "Number" and generating a code that calls JavaScript's `-` directly.

### PR DESCRIPTION
**Pull request by noahmorrison**
As opposed to $negate(4) we now do -4

Closes #66

### CODE REVIEW

File: src/transform/negate.js [hunk 1]
```diff
@@ -2,8 +2,13 @@ var es = require("../es");
 
 function Negate(transform, node) {
     var expr = transform(node.expr);
-    var negate = es.Identifier(node.loc, "$negate");
-    return es.CallExpression(null, negate, [expr]);
+    if (typeof node.expr.data === "number") {
```
Comment (wavebeem) [inline src/transform/negate.js]: This will work, but the correct check is `node.type === "Number"`. You never know what node type might have a numeric data field in the future, so please update the logic here.

File: src/transform/negate.js [hunk 2]
```diff
@@ -2,8 +2,13 @@ var es = require("../es");
...
+        var literal = es.Literal(node.loc, node.expr.data);
+        return es.UnaryExpression(node.loc, true, "-", literal);
```
Comment (wavebeem) [inline src/transform/negate.js]: The function `transform` should work here to change the `node.expr` into an ES AST node, so just use `var literal = transform(node.expr);`, please.

**Comment by wavebeem** [comment]
This works for most cases currently, but it fails on `-NaN` and produces suboptimal output for `-Infinity`. Switching to use `transform` should take care of those edge cases.

Happy to merge this once the two line notes have been addressed. Thanks for your help on Squiggle so far!

**Comment by noahmorrison** [comment]
Updated those lines for you

``` haskell
let n = -4
let ne = -n
let nNaN = -NaN
let nInf = -Infinity
in global.console.log([n, ne, nNaN, nInf].join(", "))
```

Output
`-4, 4, NaN, -Infinity`

**Comment by wavebeem** [comment]
All right, it looks good to go. Thanks again for your work on this! 👍
